services:
    zan.http_api.encoding_response_listener:
        class: Zan\HttpApiBundle\Listener\EncodingResponseListener
        arguments: ['@serializer']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    zan.http_api.exception_listener:
        class: Zan\HttpApiBundle\Listener\ExceptionListener
        arguments: ['%zan.debug.includeExceptionTraceInResponse%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
